version: "0.3"

metadata:
  name: "mysql"
  display_name: "MySQL"
  description: "Open source relational database management system"
  version: "8.0.34"
  category: "database"
  subcategory: "relational"
  tags: ["mysql", "database", "sql", "relational", "mariadb"]
  license: "GPL-2.0"
  language: "C++"
  maintainer: "Oracle Corporation"
  urls:
    website: "https://www.mysql.com"
    documentation: "https://dev.mysql.com/doc"
    source: "https://github.com/mysql/mysql-server"
    issues: "https://bugs.mysql.com"
    support: "https://www.mysql.com/support"
    download: "https://dev.mysql.com/downloads"
    changelog: "https://dev.mysql.com/doc/relnotes/mysql/8.0/en"
    license: "https://github.com/mysql/mysql-server/blob/8.0/LICENSE"
  security:
    security_contact: "secalert_us@oracle.com"
    vulnerability_disclosure: "https://www.oracle.com/security-alerts"

packages:
  - name: "server"
    package_name: "mysql-server"
    version: "8.0.34"
    alternatives: ["mysql-server-8.0"]
  - name: "client"
    package_name: "mysql-client"
    version: "8.0.34"
    alternatives: ["mysql-client-8.0"]
  - name: "common"
    package_name: "mysql-common"
    version: "8.0.34"

services:
  - name: "mysql"
    service_name: "mysql"
    type: "systemd"
    enabled: true
    config_files: ["/etc/mysql/mysql.conf.d/mysqld.cnf"]

files:
  - name: "server-config"
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    type: "config"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
  - name: "client-config"
    path: "/etc/mysql/mysql.conf.d/mysql.cnf"
    type: "config"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
  - name: "error-log"
    path: "/var/log/mysql/error.log"
    type: "log"
    owner: "mysql"
    group: "adm"
    mode: "0640"

directories:
  - name: "config"
    path: "/etc/mysql"
    owner: "root"
    group: "root"
    mode: "0755"
  - name: "data"
    path: "/var/lib/mysql"
    owner: "mysql"
    group: "mysql"
    mode: "0750"

commands:
  - name: "mysql"
    path: "/usr/bin/mysql"
    shell_completion: true
    man_page: "mysql(1)"
  - name: "mysqld"
    path: "/usr/sbin/mysqld"
    shell_completion: false
    man_page: "mysqld(8)"

ports:
  - port: 3306
    protocol: "tcp"
    service: "mysql"
    description: "MySQL server"

providers:
  apt:
    packages:
      - name: "server"
        package_name: "mysql-server"
        version: "8.0.34"
      - name: "client"
        package_name: "mysql-client"
        version: "8.0.34"

  dnf:
    packages:
      - name: "server"
        package_name: "mysql-server"
        version: "8.0.34"
      - name: "client"
        package_name: "mysql"
        version: "8.0.34"

  brew:
    packages:
      - name: "mysql"
        package_name: "mysql"
        version: "8.0.34"

  choco:
    packages:
      - name: "mysql"
        package_name: "mysql"
        version: "8.0.34"

  docker:
    containers:
      - name: "mysql"
        image: "mysql"
        tag: "8.0.34"
        registry: "docker.io"
        ports: ["3306:3306"]
        volumes: ["/var/lib/mysql:/var/lib/mysql"]

compatibility:
  matrix:
    - provider: "apt"
      platform: ["ubuntu", "debian"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
    - provider: "dnf"
      platform: ["fedora", "rhel", "centos", "rocky", "alma"]
      architecture: ["amd64", "arm64"]
      supported: true
    - provider: "brew"
      platform: "macos"
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
    - provider: "docker"
      platform: ["linux", "macos", "windows"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
