version: '0.3'
metadata:
  name: terraform
  display_name: Terraform
  description: Infrastructure as Code tool for building, changing, and versioning infrastructure
  version: 1.5.0
  category: infrastructure
  subcategory: iac
  tags:
  - terraform
  - infrastructure
  - iac
  - devops
  - cloud
  license: MPL-2.0
  language: Go
  maintainer: HashiCorp
  urls:
    website: https://www.terraform.io
    documentation: https://www.terraform.io/docs
    source: https://github.com/hashicorp/terraform
    issues: https://github.com/hashicorp/terraform/issues
    support: https://www.terraform.io/community
    download: https://releases.hashicorp.com/terraform
    changelog: https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md
    license: https://github.com/hashicorp/terraform/blob/main/LICENSE
  security:
    security_contact: security@hashicorp.com
    vulnerability_disclosure: https://www.hashicorp.com/security
packages:
- name: terraform
  package_name: terraform
  version: 1.5.0
binaries:
- name: terraform
  url: https://releases.hashicorp.com/terraform/{{version}}/terraform_{{version}}_{{platform}}_{{architecture}}.zip
  version: 1.5.0
  checksum: sha256:9e9f3e6750a640d3f27f9b5f6b1e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e
  archive:
    format: zip
    strip_components: 0
  install_path: /usr/local/bin/terraform
  platform_map:
    linux: linux
    darwin: darwin
    windows: windows
  architecture_map:
    amd64: amd64
    arm64: arm64
files:
- name: config
  path: ~/.terraformrc
  type: config
  owner: $(whoami)
  group: $(whoami)
  mode: '0644'
  backup: true
directories:
- name: config
  path: ~/.terraform.d
  owner: $(whoami)
  group: $(whoami)
  mode: '0755'
- name: plugins
  path: ~/.terraform.d/plugins
  owner: $(whoami)
  group: $(whoami)
  mode: '0755'
commands:
- name: terraform
  path: /usr/local/bin/terraform
  shell_completion: true
  aliases:
  - tf
providers:
  apt:
    repositories:
    - name: hashicorp
      url: https://apt.releases.hashicorp.com
      key: https://apt.releases.hashicorp.com/gpg
      type: upstream
      recommended: true
      packages:
      - name: terraform
        package_name: terraform
  dnf:
    repositories:
    - name: hashicorp
      url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      type: upstream
      recommended: true
      packages:
      - name: terraform
        package_name: terraform
  brew:
    packages:
    - name: terraform
      package_name: terraform
  choco:
    packages:
    - name: terraform
      package_name: terraform
compatibility:
  matrix:
  - provider: apt
    platform:
    - ubuntu
    - debian
    architecture:
    - amd64
    - arm64
    supported: true
    recommended: true
  - provider: dnf
    platform:
    - fedora
    - rhel
    - centos
    - rocky
    - alma
    architecture:
    - amd64
    - arm64
    supported: true
  - provider: brew
    platform: macos
    architecture:
    - amd64
    - arm64
    supported: true
    recommended: true
  - provider: choco
    platform: windows
    architecture:
    - amd64
    supported: true
