version: '1.0'
repositories:
- name: brew-macos
  type: brew
  platform: macos
  distribution:
  - macos
  architecture:
  - x86_64
  - arm64
  endpoints:
    packages: https://formulae.brew.sh/api/formula.json
    search: https://formulae.brew.sh/api/formula/{query}.json
    info: https://formulae.brew.sh/api/formula/{package}.json
  parsing:
    format: json
    encoding: utf-8
    fields:
      name: name
      version: versions.stable
      description: desc
      homepage: homepage
      license: license
      dependencies: dependencies
  cache:
    ttl_hours: 168
    max_size_mb: 50
  limits:
    requests_per_minute: 120
    timeout_seconds: 180
  metadata:
    description: Homebrew Core Formulae
    maintainer: Homebrew
    priority: 95
    enabled: true
    official: true
    url: https://formulae.brew.sh
  eol: false
  query_type: bulk_download
- name: brew-cask-macos
  type: brew
  platform: macos
  distribution:
  - macos
  architecture:
  - x86_64
  - arm64
  endpoints:
    packages: https://formulae.brew.sh/api/cask.json
    search: https://formulae.brew.sh/api/cask/{query}.json
    info: https://formulae.brew.sh/api/cask/{package}.json
  parsing:
    format: json
    encoding: utf-8
    fields:
      name: token
      version: version
      description: desc
      homepage: homepage
  cache:
    ttl_hours: 168
    max_size_mb: 30
  metadata:
    description: Homebrew Cask Applications
    maintainer: Homebrew
    priority: 90
    enabled: true
    official: true
    url: https://formulae.brew.sh/cask
  eol: false
  query_type: bulk_download
