version: "1.0"
repositories:
  # JavaScript/Node.js
  - name: "npm-registry"
    type: "npm"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://registry.npmjs.org/-/all"
      search: "https://registry.npmjs.org/-/v1/search?text={query}&size=250"
      info: "https://registry.npmjs.org/{package}"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "dist-tags.latest"
        description: "description"
        homepage: "homepage"
        license: "license"
        maintainer: "maintainers"
        dependencies: "dependencies"
    cache:
      ttl_hours: 6
      max_size_mb: 500
    limits:
      requests_per_minute: 300
      timeout_seconds: 180
    metadata:
      description: "NPM Registry"
      maintainer: "npm, Inc."
      priority: 95
      enabled: true
      official: true
      url: "https://www.npmjs.com"

  # Python
  - name: "pypi"
    type: "pypi"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://pypi.org/simple/"
      search: "https://pypi.org/search/?q={query}&o=-created"
      info: "https://pypi.org/pypi/{package}/json"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "info.name"
        version: "info.version"
        description: "info.summary"
        homepage: "info.home_page"
        license: "info.license"
        maintainer: "info.maintainer"
        category: "info.classifiers"
    cache:
      ttl_hours: 12
      max_size_mb: 300
    limits:
      requests_per_minute: 600
      timeout_seconds: 120
    metadata:
      description: "Python Package Index"
      maintainer: "Python Software Foundation"
      priority: 95
      enabled: true
      official: true
      url: "https://pypi.org"

  - name: "conda-forge"
    type: "conda"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://conda.anaconda.org/conda-forge/channeldata.json"
      search: "https://anaconda.org/search?q={query}"
      info: "https://anaconda.org/conda-forge/{package}"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "summary"
        homepage: "home"
        license: "license"
    cache:
      ttl_hours: 24
      max_size_mb: 200
    metadata:
      description: "Conda Forge"
      maintainer: "conda-forge"
      priority: 85
      enabled: true
      official: true
      url: "https://conda-forge.org"

  # Rust
  - name: "crates-io"
    type: "cargo"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://crates.io/api/v1/crates"
      search: "https://crates.io/api/v1/crates?q={query}&per_page=100"
      info: "https://crates.io/api/v1/crates/{package}"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "crate.name"
        version: "crate.newest_version"
        description: "crate.description"
        homepage: "crate.homepage"
        license: "crate.license"
        category: "crate.categories"
    cache:
      ttl_hours: 12
      max_size_mb: 100
    limits:
      requests_per_minute: 300
      timeout_seconds: 120
    metadata:
      description: "Crates.io Rust Package Registry"
      maintainer: "The Rust Foundation"
      priority: 95
      enabled: true
      official: true
      url: "https://crates.io"

  # Ruby
  - name: "rubygems"
    type: "gem"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://rubygems.org/api/v1/gems.json"
      search: "https://rubygems.org/api/v1/search.json?query={query}"
      info: "https://rubygems.org/api/v1/gems/{package}.json"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "info"
        homepage: "homepage_uri"
        license: "licenses"
        maintainer: "authors"
    cache:
      ttl_hours: 12
      max_size_mb: 150
    metadata:
      description: "RubyGems.org"
      maintainer: "Ruby Central"
      priority: 95
      enabled: true
      official: true
      url: "https://rubygems.org"

  # Go
  - name: "go-packages"
    type: "go"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://pkg.go.dev/search?q={query}&m=package"
      search: "https://pkg.go.dev/search?q={query}"
      info: "https://pkg.go.dev/{package}"
    parsing:
      format: "html"
      encoding: "utf-8"
      # Custom parser needed for Go packages
      custom_parser: "go_packages_parser"
    cache:
      ttl_hours: 24
      max_size_mb: 100
    metadata:
      description: "Go Packages"
      maintainer: "Google"
      priority: 90
      enabled: true
      official: true
      url: "https://pkg.go.dev"

  # PHP
  - name: "packagist"
    type: "composer"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://packagist.org/packages/list.json"
      search: "https://packagist.org/search.json?q={query}&per_page=100"
      info: "https://packagist.org/packages/{package}.json"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "description"
        homepage: "homepage"
        license: "license"
        maintainer: "authors"
    cache:
      ttl_hours: 12
      max_size_mb: 200
    metadata:
      description: "Packagist PHP Repository"
      maintainer: "Packagist"
      priority: 95
      enabled: true
      official: true
      url: "https://packagist.org"

  # .NET
  - name: "nuget-org"
    type: "nuget"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://api.nuget.org/v3-flatcontainer/"
      search: "https://azuresearch-usnc.nuget.org/query?q={query}&take=100"
      info: "https://api.nuget.org/v3-flatcontainer/{package}/index.json"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "id"
        version: "version"
        description: "description"
        homepage: "projectUrl"
        license: "licenseUrl"
        maintainer: "authors"
        tags: "tags"
    cache:
      ttl_hours: 12
      max_size_mb: 200
    metadata:
      description: "NuGet Gallery"
      maintainer: "Microsoft"
      priority: 95
      enabled: true
      official: true
      url: "https://www.nuget.org"

  # Java
  - name: "maven-central"
    type: "maven"
    platform: "universal"
    distribution: ["universal"]
    architecture: ["all"]
    endpoints:
      packages: "https://search.maven.org/solrsearch/select?q=*:*&rows=50000&wt=json"
      search: "https://search.maven.org/solrsearch/select?q={query}&rows=100&wt=json"
      info: "https://search.maven.org/solrsearch/select?q=g:{group}+AND+a:{artifact}&wt=json"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "response.docs.a"
        version: "response.docs.latestVersion"
        description: "response.docs.text"
        maintainer: "response.docs.g"
    cache:
      ttl_hours: 24
      max_size_mb: 300
    metadata:
      description: "Maven Central Repository"
      maintainer: "Sonatype"
      priority: 95
      enabled: true
      official: true
      url: "https://search.maven.org"