version: "1.0"
repositories:
  # APT-based distributions
  - name: "ubuntu-main"
    type: "apt"
    platform: "linux"
    distribution: ["ubuntu"]
    architecture: ["amd64", "arm64", "armhf"]
    endpoints:
      packages: "http://archive.ubuntu.com/ubuntu/dists/jammy/main/binary-{arch}/Packages.gz"
      search: "https://packages.ubuntu.com/search?keywords={query}"
      info: "https://packages.ubuntu.com/jammy/{package}"
    parsing:
      format: "debian_packages"
      compression: "gzip"
      encoding: "utf-8"
      fields:
        name: "Package"
        version: "Version"
        description: "Description"
        maintainer: "Maintainer"
        homepage: "Homepage"
        dependencies: "Depends"
        size: "Installed-Size"
        category: "Section"
        download_url: "Filename"
    cache:
      ttl_hours: 24
      max_size_mb: 100
    limits:
      requests_per_minute: 60
      timeout_seconds: 300
    metadata:
      description: "Ubuntu Main Repository"
      maintainer: "Ubuntu"
      priority: 90
      enabled: true
      official: true
      url: "https://packages.ubuntu.com"

  - name: "debian-main"
    type: "apt"
    platform: "linux"
    distribution: ["debian"]
    architecture: ["amd64", "arm64", "armhf", "i386"]
    endpoints:
      packages: "http://deb.debian.org/debian/dists/bookworm/main/binary-{arch}/Packages.gz"
      search: "https://packages.debian.org/search?keywords={query}"
      info: "https://packages.debian.org/bookworm/{package}"
    parsing:
      format: "debian_packages"
      compression: "gzip"
      encoding: "utf-8"
      fields:
        name: "Package"
        version: "Version"
        description: "Description"
        maintainer: "Maintainer"
        homepage: "Homepage"
        dependencies: "Depends"
        size: "Installed-Size"
        category: "Section"
    cache:
      ttl_hours: 24
      max_size_mb: 100
    metadata:
      description: "Debian Main Repository"
      maintainer: "Debian"
      priority: 85
      enabled: true
      official: true
      url: "https://packages.debian.org"

  # DNF/YUM-based distributions
  - name: "fedora-updates"
    type: "dnf"
    platform: "linux"
    distribution: ["fedora"]
    architecture: ["x86_64", "aarch64"]
    endpoints:
      packages: "https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch={arch}"
      search: "https://packages.fedoraproject.org/search?query={query}"
      info: "https://packages.fedoraproject.org/pkgs/{package}/"
    parsing:
      format: "rpm_metadata"
      compression: "gzip"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "description"
        maintainer: "packager"
        homepage: "url"
        license: "license"
        size: "size"
        category: "group"
    cache:
      ttl_hours: 12
      max_size_mb: 150
    metadata:
      description: "Fedora Updates Repository"
      maintainer: "Fedora Project"
      priority: 85
      enabled: true
      official: true
      url: "https://packages.fedoraproject.org"

  - name: "rhel-appstream"
    type: "dnf"
    platform: "linux"
    distribution: ["rhel", "centos", "rocky", "alma"]
    architecture: ["x86_64", "aarch64"]
    endpoints:
      packages: "https://cdn.redhat.com/content/dist/rhel9/{arch}/appstream/os/repodata/repomd.xml"
    parsing:
      format: "rpm_metadata"
      compression: "gzip"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "description"
        maintainer: "packager"
        homepage: "url"
        license: "license"
    cache:
      ttl_hours: 24
      max_size_mb: 200
    auth:
      type: "basic"
    metadata:
      description: "RHEL AppStream Repository"
      maintainer: "Red Hat"
      priority: 80
      enabled: false  # Requires subscription
      official: true

  # SUSE-based distributions
  - name: "opensuse-oss"
    type: "zypper"
    platform: "linux"
    distribution: ["opensuse", "sles"]
    architecture: ["x86_64", "aarch64"]
    endpoints:
      packages: "http://download.opensuse.org/tumbleweed/repo/oss/repodata/repomd.xml"
      search: "https://software.opensuse.org/search?q={query}"
    parsing:
      format: "rpm_metadata"
      compression: "gzip"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "description"
        maintainer: "packager"
        homepage: "url"
        license: "license"
    cache:
      ttl_hours: 24
      max_size_mb: 150
    metadata:
      description: "openSUSE OSS Repository"
      maintainer: "openSUSE"
      priority: 80
      enabled: true
      official: true
      url: "https://software.opensuse.org"

  # Arch-based distributions
  - name: "arch-core"
    type: "pacman"
    platform: "linux"
    distribution: ["arch", "manjaro", "endeavouros"]
    architecture: ["x86_64"]
    endpoints:
      packages: "https://archlinux.org/packages/core/x86_64/"
      search: "https://archlinux.org/packages/search/json/?q={query}"
      info: "https://archlinux.org/packages/core/x86_64/{package}/"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "pkgname"
        version: "pkgver"
        description: "pkgdesc"
        maintainer: "maintainers"
        homepage: "url"
        license: "licenses"
        dependencies: "depends"
    cache:
      ttl_hours: 12
      max_size_mb: 50
    metadata:
      description: "Arch Linux Core Repository"
      maintainer: "Arch Linux"
      priority: 85
      enabled: true
      official: true
      url: "https://archlinux.org/packages"

  # Alpine Linux
  - name: "alpine-main"
    type: "apk"
    platform: "linux"
    distribution: ["alpine"]
    architecture: ["x86_64", "aarch64", "armhf"]
    endpoints:
      packages: "https://dl-cdn.alpinelinux.org/alpine/v3.18/main/{arch}/APKINDEX.tar.gz"
      search: "https://pkgs.alpinelinux.org/packages?name={query}"
    parsing:
      format: "text"
      compression: "gzip"
      encoding: "utf-8"
      patterns:
        line_pattern: "^P:(.+)$"
        name_group: 1
      fields:
        name: "P"
        version: "V"
        description: "T"
        maintainer: "m"
        homepage: "U"
        license: "L"
        size: "S"
    cache:
      ttl_hours: 24
      max_size_mb: 20
    metadata:
      description: "Alpine Linux Main Repository"
      maintainer: "Alpine Linux"
      priority: 80
      enabled: true
      official: true
      url: "https://pkgs.alpinelinux.org"

  # Gentoo
  - name: "gentoo-portage"
    type: "emerge"
    platform: "linux"
    distribution: ["gentoo"]
    architecture: ["amd64", "arm64", "x86"]
    endpoints:
      packages: "https://packages.gentoo.org/packages/search?q={query}&format=json"
      search: "https://packages.gentoo.org/packages/search?q={query}"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "description"
        maintainer: "maintainer"
        homepage: "homepage"
        license: "license"
        category: "category"
    cache:
      ttl_hours: 24
      max_size_mb: 100
    metadata:
      description: "Gentoo Portage Repository"
      maintainer: "Gentoo"
      priority: 75
      enabled: true
      official: true
      url: "https://packages.gentoo.org"

  # Void Linux
  - name: "void-current"
    type: "xbps"
    platform: "linux"
    distribution: ["void"]
    architecture: ["x86_64", "aarch64"]
    endpoints:
      packages: "https://alpha.de.repo.voidlinux.org/current/{arch}-repodata"
      search: "https://voidlinux.org/packages/?q={query}"
    parsing:
      format: "text"
      compression: "gzip"
      encoding: "utf-8"
    cache:
      ttl_hours: 24
      max_size_mb: 50
    metadata:
      description: "Void Linux Repository"
      maintainer: "Void Linux"
      priority: 75
      enabled: true
      official: true
      url: "https://voidlinux.org/packages"

  # Universal Linux packages
  - name: "flathub"
    type: "flatpak"
    platform: "linux"
    distribution: ["universal"]
    architecture: ["x86_64", "aarch64"]
    endpoints:
      packages: "https://flathub.org/api/v2/appstream"
      search: "https://flathub.org/api/v1/apps/search/{query}"
      info: "https://flathub.org/api/v1/apps/{package}"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "flatpakAppId"
        version: "currentReleaseVersion"
        description: "summary"
        homepage: "projectLicense"
        category: "categories"
    cache:
      ttl_hours: 12
      max_size_mb: 100
    metadata:
      description: "Flathub Repository"
      maintainer: "Flathub"
      priority: 70
      enabled: true
      official: true
      url: "https://flathub.org"

  - name: "snapcraft"
    type: "snap"
    platform: "linux"
    distribution: ["ubuntu", "fedora", "debian", "opensuse", "arch"]
    architecture: ["amd64", "arm64", "armhf"]
    endpoints:
      packages: "https://api.snapcraft.io/v2/snaps/find"
      search: "https://api.snapcraft.io/v2/snaps/find?q={query}"
      info: "https://api.snapcraft.io/v2/snaps/info/{package}"
    parsing:
      format: "json"
      encoding: "utf-8"
      fields:
        name: "name"
        version: "version"
        description: "summary"
        maintainer: "publisher.display-name"
        category: "categories"
    cache:
      ttl_hours: 12
      max_size_mb: 100
    metadata:
      description: "Snap Store"
      maintainer: "Canonical"
      priority: 65
      enabled: true
      official: true
      url: "https://snapcraft.io"