version: '1.0'
repositories:
- name: zypper-opensuse-leap-15
  type: zypper
  platform: linux
  distribution:
  - opensuse
  architecture:
  - x86_64
  - aarch64
  version_mapping:
    '15': leap-15
  endpoints:
    packages: http://download.opensuse.org/distribution/leap/15.5/repo/oss/repodata/repomd.xml
    search: https://software.opensuse.org/search?q={query}
  parsing:
    format: rpm_metadata
    compression: gzip
    encoding: utf-8
    fields:
      name: name
      version: version
      description: description
      maintainer: packager
      homepage: url
      license: license
  cache:
    ttl_hours: 168
    max_size_mb: 150
  metadata:
    description: openSUSE Leap 15 OSS Repository
    maintainer: openSUSE
    priority: 80
    enabled: true
    official: true
    url: https://software.opensuse.org
  eol: false
  query_type: bulk_download
- name: zypper-opensuse-tumbleweed
  type: zypper
  platform: linux
  distribution:
  - opensuse
  architecture:
  - x86_64
  - aarch64
  version_mapping:
    '0': tumbleweed
  endpoints:
    packages: http://download.opensuse.org/tumbleweed/repo/oss/repodata/repomd.xml
    search: https://software.opensuse.org/search?q={query}
  parsing:
    format: rpm_metadata
    compression: gzip
    encoding: utf-8
    fields:
      name: name
      version: version
      description: description
      maintainer: packager
      homepage: url
      license: license
  cache:
    ttl_hours: 168
    max_size_mb: 150
  metadata:
    description: openSUSE Tumbleweed OSS Repository
    maintainer: openSUSE
    priority: 80
    enabled: true
    official: true
    url: https://software.opensuse.org
  eol: false
  query_type: bulk_download
- name: zypper-sles-12
  type: zypper
  platform: linux
  distribution:
  - sles
  architecture:
  - x86_64
  - aarch64
  version_mapping:
    '12': '12'
  endpoints:
    packages: https://updates.suse.com/SUSE/Products/SLE-Product-SLES/12-SP5/{arch}/product/repodata/repomd.xml
  parsing:
    format: rpm_metadata
    compression: gzip
    encoding: utf-8
    fields:
      name: name
      version: version
      description: description
      maintainer: packager
      homepage: url
      license: license
  cache:
    ttl_hours: 168
    max_size_mb: 150
  auth:
    type: basic
  metadata:
    description: SUSE Linux Enterprise Server 12 Repository
    maintainer: SUSE
    priority: 75
    enabled: false
    official: true
  eol: true
  query_type: bulk_download
- name: zypper-sles-15
  type: zypper
  platform: linux
  distribution:
  - sles
  architecture:
  - x86_64
  - aarch64
  version_mapping:
    '15': '15'
  endpoints:
    packages: https://updates.suse.com/SUSE/Products/SLE-Product-SLES/15-SP5/{arch}/product/repodata/repomd.xml
  parsing:
    format: rpm_metadata
    compression: gzip
    encoding: utf-8
    fields:
      name: name
      version: version
      description: description
      maintainer: packager
      homepage: url
      license: license
  cache:
    ttl_hours: 168
    max_size_mb: 150
  auth:
    type: basic
  metadata:
    description: SUSE Linux Enterprise Server 15 Repository
    maintainer: SUSE
    priority: 75
    enabled: false
    official: true
  eol: false
  query_type: bulk_download
