version: "0.2"

metadata:
  name: "ansible"
  display_name: "Ansible"
  description: "Automation platform for configuration management, application deployment, and orchestration"
  version: "8.0.0"
  category: "automation"
  subcategory: "configuration-management"
  tags: ["ansible", "automation", "configuration", "devops", "orchestration"]
  license: "GPL-3.0"
  language: "Python"
  maintainer: "Red Hat Inc."
  urls:
    website: "https://www.ansible.com"
    documentation: "https://docs.ansible.com"
    source: "https://github.com/ansible/ansible"
    issues: "https://github.com/ansible/ansible/issues"
    support: "https://www.ansible.com/community"
    download: "https://pypi.org/project/ansible"
    changelog: "https://github.com/ansible/ansible/blob/devel/changelogs/CHANGELOG-v8.rst"
    license: "https://github.com/ansible/ansible/blob/devel/COPYING"
  security:
    security_contact: "security@ansible.com"
    vulnerability_disclosure: "https://www.ansible.com/security"

packages:
  - name: "core"
    version: "2.15.0"
    alternatives: ["ansible-core"]
  - name: "ansible"
    version: "8.0.0"
    alternatives: ["ansible"]

files:
  - name: "config"
    path: "/etc/ansible/ansible.cfg"
    type: "config"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
  - name: "hosts"
    path: "/etc/ansible/hosts"
    type: "config"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
  - name: "user-config"
    path: "~/.ansible.cfg"
    type: "config"
    owner: "$(whoami)"
    group: "$(whoami)"
    mode: "0644"
    backup: true
  - name: "log"
    path: "/var/log/ansible.log"
    type: "log"
    owner: "root"
    group: "root"
    mode: "0644"

directories:
  - name: "config"
    path: "/etc/ansible"
    owner: "root"
    group: "root"
    mode: "0755"
  - name: "playbooks"
    path: "/etc/ansible/playbooks"
    owner: "root"
    group: "root"
    mode: "0755"
  - name: "roles"
    path: "/etc/ansible/roles"
    owner: "root"
    group: "root"
    mode: "0755"
  - name: "collections"
    path: "~/.ansible/collections"
    owner: "$(whoami)"
    group: "$(whoami)"
    mode: "0755"

commands:
  - name: "ansible"
    path: "/usr/bin/ansible"
    shell_completion: true
    man_page: "ansible(1)"
  - name: "ansible-playbook"
    path: "/usr/bin/ansible-playbook"
    shell_completion: true
    man_page: "ansible-playbook(1)"
  - name: "ansible-galaxy"
    path: "/usr/bin/ansible-galaxy"
    shell_completion: true
    man_page: "ansible-galaxy(1)"
  - name: "ansible-vault"
    path: "/usr/bin/ansible-vault"
    shell_completion: true
    man_page: "ansible-vault(1)"

providers:
  apt:
    actions: ["install", "uninstall", "upgrade", "info"]
    packages:
      - name: "ansible"
        alternatives: ["ansible"]
    repositories:
      - name: "ubuntu-default"
        type: "os-default"
        packages:
          - name: "ansible"
            alternatives: ["ansible"]

  dnf:
    actions: ["install", "uninstall", "upgrade", "info"]
    packages:
      - name: "ansible"
        alternatives: ["ansible"]

  brew:
    actions: ["install", "uninstall", "upgrade", "info"]
    packages:
      - name: "ansible"
        alternatives: ["ansible"]

  pypi:
    actions: ["install", "uninstall", "upgrade", "info"]
    packages:
      - name: "ansible"
        alternatives: ["ansible"]
      - name: "core"
        alternatives: ["ansible-core"]

  docker:
    actions: ["install", "start", "stop", "restart", "status"]
    containers:
      - name: "ansible"
        image: "ansible/ansible-runner"
        tag: "latest"
        registry: "docker.io"
        volumes: ["/etc/ansible:/etc/ansible", "/var/log/ansible:/var/log/ansible"]
        environment:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        labels:
          purpose: "automation-platform"

compatibility:
  matrix:
    - provider: "apt"
      platform: ["ubuntu", "debian"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
      tested: true
    - provider: "dnf"
      platform: ["fedora", "rhel", "centos"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
    - provider: "brew"
      platform: "macos"
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
    - provider: "pypi"
      platform: ["linux", "macos", "windows"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
      notes: "Recommended installation method"
    - provider: "docker"
      platform: ["linux", "macos", "windows"]
      architecture: ["amd64", "arm64"]
      supported: true
      notes: "Containerized execution environment"